// Hardcoded city data keyed by ISO 3166-1 alpha-2 country codes.
// Slugs must match myservice.pk URL slugs: lowercase, hyphen-separated.
export const CITIES = {
  af: [
    { name: 'Kabul', slug: 'kabul' },
    { name: 'Herat', slug: 'herat' },
    { name: 'Mazar-i-Sharif', slug: 'mazar-i-sharif' },
    { name: 'Kandahar', slug: 'kandahar' },
    { name: 'Jalalabad', slug: 'jalalabad' },
  ],
  al: [
    { name: 'Tirana', slug: 'tirana' },
    { name: 'Durrës', slug: 'durres' },
    { name: 'Vlorë', slug: 'vlore' },
    { name: 'Sarandë', slug: 'sarande' },
    { name: 'Shkodër', slug: 'shkoder' },
    { name: 'Berat', slug: 'berat' },
    { name: 'Gjirokastër', slug: 'gjirokaster' },
  ],
  dz: [
    { name: 'Algiers', slug: 'algiers' },
    { name: 'Oran', slug: 'oran' },
    { name: 'Constantine', slug: 'constantine' },
    { name: 'Annaba', slug: 'annaba' },
    { name: 'Tlemcen', slug: 'tlemcen' },
    { name: 'Ghardaïa', slug: 'ghardaia' },
  ],
  as: [
    { name: 'Pago Pago', slug: 'pago-pago' },
    { name: 'Tafuna', slug: 'tafuna' },
    { name: 'Leone', slug: 'leone' },
  ],
  ad: [
    { name: 'Andorra la Vella', slug: 'andorra-la-vella' },
    { name: 'Escaldes-Engordany', slug: 'escaldes-engordany' },
    { name: 'Encamp', slug: 'encamp' },
    { name: 'La Massana', slug: 'la-massana' },
    { name: 'Soldeu', slug: 'soldeu' },
  ],
  ao: [
    { name: 'Luanda', slug: 'luanda' },
    { name: 'Huambo', slug: 'huambo' },
    { name: 'Lobito', slug: 'lobito' },
    { name: 'Benguela', slug: 'benguela' },
    { name: 'Lubango', slug: 'lubango' },
  ],
  ai: [
    { name: 'The Valley', slug: 'the-valley' },
    { name: 'Blowing Point', slug: 'blowing-point' },
    { name: 'Sandy Ground', slug: 'sandy-ground' },
  ],
  ag: [
    { name: "St. John's", slug: 'st-johns' },
    { name: 'English Harbour', slug: 'english-harbour' },
    { name: 'Jolly Harbour', slug: 'jolly-harbour' },
    { name: 'Codrington', slug: 'codrington' },
  ],
  ar: [
    { name: 'Buenos Aires', slug: 'buenos-aires' },
    { name: 'Bariloche', slug: 'bariloche' },
    { name: 'Mendoza', slug: 'mendoza' },
    { name: 'Córdoba', slug: 'cordoba' },
    { name: 'Salta', slug: 'salta' },
    { name: 'Ushuaia', slug: 'ushuaia' },
    { name: 'El Calafate', slug: 'el-calafate' },
    { name: 'Mar del Plata', slug: 'mar-del-plata' },
    { name: 'Iguazu', slug: 'iguazu' },
    { name: 'Rosario', slug: 'rosario' },
  ],
  am: [
    { name: 'Yerevan', slug: 'yerevan' },
    { name: 'Gyumri', slug: 'gyumri' },
    { name: 'Dilijan', slug: 'dilijan' },
    { name: 'Tsaghkadzor', slug: 'tsaghkadzor' },
    { name: 'Jermuk', slug: 'jermuk' },
    { name: 'Vanadzor', slug: 'vanadzor' },
  ],
  aw: [
    { name: 'Oranjestad', slug: 'oranjestad' },
    { name: 'Palm Beach', slug: 'palm-beach' },
    { name: 'Eagle Beach', slug: 'eagle-beach' },
    { name: 'Noord', slug: 'noord' },
    { name: 'San Nicolas', slug: 'san-nicolas' },
  ],
  au: [
    { name: 'Sydney', slug: 'sydney' },
    { name: 'Melbourne', slug: 'melbourne' },
    { name: 'Brisbane', slug: 'brisbane' },
    { name: 'Perth', slug: 'perth' },
    { name: 'Adelaide', slug: 'adelaide' },
    { name: 'Gold Coast', slug: 'gold-coast' },
    { name: 'Cairns', slug: 'cairns' },
    { name: 'Darwin', slug: 'darwin' },
    { name: 'Hobart', slug: 'hobart' },
    { name: 'Canberra', slug: 'canberra' },
    { name: 'Alice Springs', slug: 'alice-springs' },
    { name: 'Uluru', slug: 'uluru' },
  ],
  at: [
    { name: 'Vienna', slug: 'vienna' },
    { name: 'Salzburg', slug: 'salzburg' },
    { name: 'Innsbruck', slug: 'innsbruck' },
    { name: 'Graz', slug: 'graz' },
    { name: 'Linz', slug: 'linz' },
    { name: 'Hallstatt', slug: 'hallstatt' },
    { name: 'Kitzbühel', slug: 'kitzbuhel' },
    { name: 'Zell am See', slug: 'zell-am-see' },
    { name: 'Bad Gastein', slug: 'bad-gastein' },
  ],
  az: [
    { name: 'Baku', slug: 'baku' },
    { name: 'Ganja', slug: 'ganja' },
    { name: 'Sheki', slug: 'sheki' },
    { name: 'Gabala', slug: 'gabala' },
    { name: 'Quba', slug: 'quba' },
    { name: 'Lankaran', slug: 'lankaran' },
  ],
  bs: [
    { name: 'Nassau', slug: 'nassau' },
    { name: 'Paradise Island', slug: 'paradise-island' },
    { name: 'Freeport', slug: 'freeport' },
    { name: 'Exuma', slug: 'exuma' },
    { name: 'Eleuthera', slug: 'eleuthera' },
    { name: 'Bimini', slug: 'bimini' },
  ],
  bh: [
    { name: 'Manama', slug: 'manama' },
    { name: 'Riffa', slug: 'riffa' },
    { name: 'Muharraq', slug: 'muharraq' },
    { name: 'Juffair', slug: 'juffair' },
    { name: 'Seef', slug: 'seef' },
    { name: 'Adliya', slug: 'adliya' },
  ],
  bd: [
    { name: 'Dhaka', slug: 'dhaka' },
    { name: 'Chittagong', slug: 'chittagong' },
    { name: "Cox's Bazar", slug: 'coxs-bazar' },
    { name: 'Sylhet', slug: 'sylhet' },
    { name: 'Rajshahi', slug: 'rajshahi' },
    { name: 'Khulna', slug: 'khulna' },
    { name: 'Barisal', slug: 'barisal' },
    { name: 'Rangpur', slug: 'rangpur' },
  ],
  bb: [
    { name: 'Bridgetown', slug: 'bridgetown' },
    { name: 'Holetown', slug: 'holetown' },
    { name: 'Speightstown', slug: 'speightstown' },
    { name: 'Oistins', slug: 'oistins' },
    { name: 'St. Lawrence Gap', slug: 'st-lawrence-gap' },
  ],
  by: [
    { name: 'Minsk', slug: 'minsk' },
    { name: 'Brest', slug: 'brest' },
    { name: 'Grodno', slug: 'grodno' },
    { name: 'Vitebsk', slug: 'vitebsk' },
    { name: 'Gomel', slug: 'gomel' },
    { name: 'Mogilev', slug: 'mogilev' },
  ],
  be: [
    { name: 'Brussels', slug: 'brussels' },
    { name: 'Bruges', slug: 'bruges' },
    { name: 'Antwerp', slug: 'antwerp' },
    { name: 'Ghent', slug: 'ghent' },
    { name: 'Leuven', slug: 'leuven' },
    { name: 'Liège', slug: 'liege' },
    { name: 'Namur', slug: 'namur' },
    { name: 'Ostend', slug: 'ostend' },
  ],
  bz: [
    { name: 'Belize City', slug: 'belize-city' },
    { name: 'San Pedro', slug: 'san-pedro' },
    { name: 'Caye Caulker', slug: 'caye-caulker' },
    { name: 'Placencia', slug: 'placencia' },
    { name: 'San Ignacio', slug: 'san-ignacio' },
    { name: 'Hopkins', slug: 'hopkins' },
  ],
  bj: [
    { name: 'Cotonou', slug: 'cotonou' },
    { name: 'Porto-Novo', slug: 'porto-novo' },
    { name: 'Parakou', slug: 'parakou' },
    { name: 'Abomey', slug: 'abomey' },
    { name: 'Ouidah', slug: 'ouidah' },
  ],
  bm: [
    { name: 'Hamilton', slug: 'hamilton' },
    { name: 'St. George', slug: 'st-george' },
    { name: 'Southampton', slug: 'southampton' },
    { name: 'Paget', slug: 'paget' },
    { name: 'Sandys', slug: 'sandys' },
  ],
  bt: [
    { name: 'Thimphu', slug: 'thimphu' },
    { name: 'Paro', slug: 'paro' },
    { name: 'Punakha', slug: 'punakha' },
    { name: 'Bumthang', slug: 'bumthang' },
    { name: 'Wangdue Phodrang', slug: 'wangdue-phodrang' },
    { name: 'Phuentsholing', slug: 'phuentsholing' },
  ],
  bo: [
    { name: 'La Paz', slug: 'la-paz' },
    { name: 'Santa Cruz', slug: 'santa-cruz' },
    { name: 'Cochabamba', slug: 'cochabamba' },
    { name: 'Sucre', slug: 'sucre' },
    { name: 'Uyuni', slug: 'uyuni' },
    { name: 'Copacabana', slug: 'copacabana' },
    { name: 'Potosí', slug: 'potosi' },
  ],
  ba: [
    { name: 'Sarajevo', slug: 'sarajevo' },
    { name: 'Mostar', slug: 'mostar' },
    { name: 'Banja Luka', slug: 'banja-luka' },
    { name: 'Tuzla', slug: 'tuzla' },
    { name: 'Međugorje', slug: 'medugorje' },
    { name: 'Jajce', slug: 'jajce' },
  ],
  bw: [
    { name: 'Gaborone', slug: 'gaborone' },
    { name: 'Francistown', slug: 'francistown' },
    { name: 'Maun', slug: 'maun' },
    { name: 'Kasane', slug: 'kasane' },
    { name: 'Ghanzi', slug: 'ghanzi' },
  ],
  br: [
    { name: 'Rio de Janeiro', slug: 'rio-de-janeiro' },
    { name: 'São Paulo', slug: 'sao-paulo' },
    { name: 'Salvador', slug: 'salvador' },
    { name: 'Fortaleza', slug: 'fortaleza' },
    { name: 'Recife', slug: 'recife' },
    { name: 'Manaus', slug: 'manaus' },
    { name: 'Florianópolis', slug: 'florianopolis' },
    { name: 'Brasília', slug: 'brasilia' },
    { name: 'Curitiba', slug: 'curitiba' },
    { name: 'Belo Horizonte', slug: 'belo-horizonte' },
    { name: 'Iguazu Falls', slug: 'iguazu-falls' },
    { name: 'Natal', slug: 'natal' },
  ],
  vg: [
    { name: 'Road Town', slug: 'road-town' },
    { name: 'Virgin Gorda', slug: 'virgin-gorda' },
    { name: 'Tortola', slug: 'tortola' },
    { name: 'Anegada', slug: 'anegada' },
    { name: 'Jost Van Dyke', slug: 'jost-van-dyke' },
  ],
  bn: [
    { name: 'Bandar Seri Begawan', slug: 'bandar-seri-begawan' },
    { name: 'Kuala Belait', slug: 'kuala-belait' },
    { name: 'Seria', slug: 'seria' },
    { name: 'Tutong', slug: 'tutong' },
    { name: 'Bangar', slug: 'bangar' },
  ],
  bg: [
    { name: 'Sofia', slug: 'sofia' },
    { name: 'Plovdiv', slug: 'plovdiv' },
    { name: 'Varna', slug: 'varna' },
    { name: 'Burgas', slug: 'burgas' },
    { name: 'Sunny Beach', slug: 'sunny-beach' },
    { name: 'Bansko', slug: 'bansko' },
    { name: 'Nessebar', slug: 'nessebar' },
    { name: 'Veliko Tarnovo', slug: 'veliko-tarnovo' },
    { name: 'Ruse', slug: 'ruse' },
  ],
  bf: [
    { name: 'Ouagadougou', slug: 'ouagadougou' },
    { name: 'Bobo-Dioulasso', slug: 'bobo-dioulasso' },
    { name: 'Koudougou', slug: 'koudougou' },
    { name: 'Ouahigouya', slug: 'ouahigouya' },
  ],
  bi: [
    { name: 'Bujumbura', slug: 'bujumbura' },
    { name: 'Gitega', slug: 'gitega' },
    { name: 'Ngozi', slug: 'ngozi' },
    { name: 'Rumonge', slug: 'rumonge' },
  ],
  kh: [
    { name: 'Phnom Penh', slug: 'phnom-penh' },
    { name: 'Siem Reap', slug: 'siem-reap' },
    { name: 'Sihanoukville', slug: 'sihanoukville' },
    { name: 'Battambang', slug: 'battambang' },
    { name: 'Kampot', slug: 'kampot' },
    { name: 'Kep', slug: 'kep' },
    { name: 'Koh Rong', slug: 'koh-rong' },
  ],
  cm: [
    { name: 'Yaoundé', slug: 'yaounde' },
    { name: 'Douala', slug: 'douala' },
    { name: 'Bamenda', slug: 'bamenda' },
    { name: 'Bafoussam', slug: 'bafoussam' },
    { name: 'Garoua', slug: 'garoua' },
    { name: 'Limbe', slug: 'limbe' },
  ],
  ca: [
    { name: 'Toronto', slug: 'toronto' },
    { name: 'Vancouver', slug: 'vancouver' },
    { name: 'Montreal', slug: 'montreal' },
    { name: 'Calgary', slug: 'calgary' },
    { name: 'Ottawa', slug: 'ottawa' },
    { name: 'Quebec City', slug: 'quebec-city' },
    { name: 'Winnipeg', slug: 'winnipeg' },
    { name: 'Victoria', slug: 'victoria' },
    { name: 'Banff', slug: 'banff' },
    { name: 'Niagara Falls', slug: 'niagara-falls' },
    { name: 'Halifax', slug: 'halifax' },
    { name: 'Whistler', slug: 'whistler' },
  ],
  cv: [
    { name: 'Praia', slug: 'praia' },
    { name: 'Mindelo', slug: 'mindelo' },
    { name: 'Santa Maria', slug: 'santa-maria' },
    { name: 'Sal Rei', slug: 'sal-rei' },
    { name: 'São Filipe', slug: 'sao-filipe' },
  ],
  bq: [
    { name: 'Kralendijk', slug: 'kralendijk' },
    { name: 'The Bottom', slug: 'the-bottom' },
    { name: 'Oranjestad', slug: 'oranjestad' },
  ],
  ky: [
    { name: 'George Town', slug: 'george-town' },
    { name: 'Seven Mile Beach', slug: 'seven-mile-beach' },
    { name: 'West Bay', slug: 'west-bay' },
    { name: 'Cayman Brac', slug: 'cayman-brac' },
    { name: 'Little Cayman', slug: 'little-cayman' },
  ],
  cf: [
    { name: 'Bangui', slug: 'bangui' },
    { name: 'Berbérati', slug: 'berberati' },
    { name: 'Bambari', slug: 'bambari' },
    { name: 'Bouar', slug: 'bouar' },
  ],
  td: [
    { name: "N'Djamena", slug: 'ndjamena' },
    { name: 'Moundou', slug: 'moundou' },
    { name: 'Sarh', slug: 'sarh' },
    { name: 'Abéché', slug: 'abeche' },
  ],
  cl: [
    { name: 'Santiago', slug: 'santiago' },
    { name: 'Valparaíso', slug: 'valparaiso' },
    { name: 'Viña del Mar', slug: 'vina-del-mar' },
    { name: 'San Pedro de Atacama', slug: 'san-pedro-de-atacama' },
    { name: 'Puerto Varas', slug: 'puerto-varas' },
    { name: 'Punta Arenas', slug: 'punta-arenas' },
    { name: 'Pucón', slug: 'pucon' },
    { name: 'Easter Island', slug: 'easter-island' },
    { name: 'La Serena', slug: 'la-serena' },
  ],
  cn: [
    { name: 'Beijing', slug: 'beijing' },
    { name: 'Shanghai', slug: 'shanghai' },
    { name: 'Guangzhou', slug: 'guangzhou' },
    { name: 'Shenzhen', slug: 'shenzhen' },
    { name: 'Chengdu', slug: 'chengdu' },
    { name: "Xi'an", slug: 'xian' },
    { name: 'Guilin', slug: 'guilin' },
    { name: 'Hangzhou', slug: 'hangzhou' },
    { name: 'Suzhou', slug: 'suzhou' },
    { name: 'Chongqing', slug: 'chongqing' },
    { name: 'Kunming', slug: 'kunming' },
    { name: 'Harbin', slug: 'harbin' },
    { name: 'Dalian', slug: 'dalian' },
    { name: 'Qingdao', slug: 'qingdao' },
  ],
  co: [
    { name: 'Bogotá', slug: 'bogota' },
    { name: 'Cartagena', slug: 'cartagena' },
    { name: 'Medellín', slug: 'medellin' },
    { name: 'Santa Marta', slug: 'santa-marta' },
    { name: 'Cali', slug: 'cali' },
    { name: 'San Andrés', slug: 'san-andres' },
    { name: 'Barranquilla', slug: 'barranquilla' },
    { name: 'Salento', slug: 'salento' },
  ],
  cr: [
    { name: 'San José', slug: 'san-jose' },
    { name: 'La Fortuna', slug: 'la-fortuna' },
    { name: 'Manuel Antonio', slug: 'manuel-antonio' },
    { name: 'Monteverde', slug: 'monteverde' },
    { name: 'Tamarindo', slug: 'tamarindo' },
    { name: 'Jacó', slug: 'jaco' },
    { name: 'Puerto Viejo', slug: 'puerto-viejo' },
    { name: 'Liberia', slug: 'liberia' },
  ],
  ci: [
    { name: 'Abidjan', slug: 'abidjan' },
    { name: 'Yamoussoukro', slug: 'yamoussoukro' },
    { name: 'Bouaké', slug: 'bouake' },
    { name: 'San-Pédro', slug: 'san-pedro' },
    { name: 'Grand-Bassam', slug: 'grand-bassam' },
  ],
  hr: [
    { name: 'Dubrovnik', slug: 'dubrovnik' },
    { name: 'Split', slug: 'split' },
    { name: 'Zagreb', slug: 'zagreb' },
    { name: 'Hvar', slug: 'hvar' },
    { name: 'Zadar', slug: 'zadar' },
    { name: 'Rovinj', slug: 'rovinj' },
    { name: 'Pula', slug: 'pula' },
    { name: 'Plitvice Lakes', slug: 'plitvice-lakes' },
    { name: 'Rijeka', slug: 'rijeka' },
    { name: 'Makarska', slug: 'makarska' },
  ],
  cu: [
    { name: 'Havana', slug: 'havana' },
    { name: 'Varadero', slug: 'varadero' },
    { name: 'Trinidad', slug: 'trinidad' },
    { name: 'Santiago de Cuba', slug: 'santiago-de-cuba' },
    { name: 'Cienfuegos', slug: 'cienfuegos' },
    { name: 'Viñales', slug: 'vinales' },
    { name: 'Cayo Coco', slug: 'cayo-coco' },
    { name: 'Holguín', slug: 'holguin' },
  ],
  cw: [
    { name: 'Willemstad', slug: 'willemstad' },
    { name: 'Jan Thiel', slug: 'jan-thiel' },
    { name: 'Westpunt', slug: 'westpunt' },
    { name: 'Sint Michiel', slug: 'sint-michiel' },
  ],
  cy: [
    { name: 'Nicosia', slug: 'nicosia' },
    { name: 'Limassol', slug: 'limassol' },
    { name: 'Paphos', slug: 'paphos' },
    { name: 'Larnaca', slug: 'larnaca' },
    { name: 'Ayia Napa', slug: 'ayia-napa' },
    { name: 'Protaras', slug: 'protaras' },
    { name: 'Kyrenia', slug: 'kyrenia' },
  ],
  cz: [
    { name: 'Prague', slug: 'prague' },
    { name: 'Brno', slug: 'brno' },
    { name: 'Český Krumlov', slug: 'cesky-krumlov' },
    { name: 'Karlovy Vary', slug: 'karlovy-vary' },
    { name: 'Ostrava', slug: 'ostrava' },
    { name: 'Plzeň', slug: 'plzen' },
    { name: 'Olomouc', slug: 'olomouc' },
    { name: 'Kutná Hora', slug: 'kutna-hora' },
  ],
  de: [
    { name: 'Berlin', slug: 'berlin' },
    { name: 'Munich', slug: 'munich' },
    { name: 'Hamburg', slug: 'hamburg' },
    { name: 'Frankfurt', slug: 'frankfurt' },
    { name: 'Cologne', slug: 'cologne' },
    { name: 'Düsseldorf', slug: 'dusseldorf' },
    { name: 'Stuttgart', slug: 'stuttgart' },
    { name: 'Dresden', slug: 'dresden' },
    { name: 'Heidelberg', slug: 'heidelberg' },
    { name: 'Nuremberg', slug: 'nuremberg' },
    { name: 'Bremen', slug: 'bremen' },
    { name: 'Leipzig', slug: 'leipzig' },
  ],
  dj: [
    { name: 'Djibouti City', slug: 'djibouti-city' },
    { name: 'Ali Sabieh', slug: 'ali-sabieh' },
    { name: 'Tadjoura', slug: 'tadjoura' },
    { name: 'Obock', slug: 'obock' },
  ],
  dk: [
    { name: 'Copenhagen', slug: 'copenhagen' },
    { name: 'Aarhus', slug: 'aarhus' },
    { name: 'Odense', slug: 'odense' },
    { name: 'Aalborg', slug: 'aalborg' },
    { name: 'Billund', slug: 'billund' },
    { name: 'Helsingør', slug: 'helsingor' },
    { name: 'Skagen', slug: 'skagen' },
  ],
  dm: [
    { name: 'Roseau', slug: 'roseau' },
    { name: 'Portsmouth', slug: 'portsmouth' },
    { name: 'Marigot', slug: 'marigot' },
    { name: 'Calibishie', slug: 'calibishie' },
  ],
  do: [
    { name: 'Santo Domingo', slug: 'santo-domingo' },
    { name: 'Punta Cana', slug: 'punta-cana' },
    { name: 'Puerto Plata', slug: 'puerto-plata' },
    { name: 'La Romana', slug: 'la-romana' },
    { name: 'Samaná', slug: 'samana' },
    { name: 'Bávaro', slug: 'bavaro' },
    { name: 'Santiago', slug: 'santiago' },
    { name: 'Cabarete', slug: 'cabarete' },
  ],
  ec: [
    { name: 'Quito', slug: 'quito' },
    { name: 'Guayaquil', slug: 'guayaquil' },
    { name: 'Cuenca', slug: 'cuenca' },
    { name: 'Galápagos', slug: 'galapagos' },
    { name: 'Baños', slug: 'banos' },
    { name: 'Montañita', slug: 'montanita' },
    { name: 'Otavalo', slug: 'otavalo' },
  ],
  eg: [
    { name: 'Cairo', slug: 'cairo' },
    { name: 'Luxor', slug: 'luxor' },
    { name: 'Aswan', slug: 'aswan' },
    { name: 'Hurghada', slug: 'hurghada' },
    { name: 'Sharm El Sheikh', slug: 'sharm-el-sheikh' },
    { name: 'Alexandria', slug: 'alexandria' },
    { name: 'Marsa Alam', slug: 'marsa-alam' },
    { name: 'El Gouna', slug: 'el-gouna' },
    { name: 'Dahab', slug: 'dahab' },
    { name: 'Siwa', slug: 'siwa' },
  ],
  sv: [
    { name: 'San Salvador', slug: 'san-salvador' },
    { name: 'Santa Ana', slug: 'santa-ana' },
    { name: 'San Miguel', slug: 'san-miguel' },
    { name: 'La Libertad', slug: 'la-libertad' },
    { name: 'Suchitoto', slug: 'suchitoto' },
  ],
  gq: [
    { name: 'Malabo', slug: 'malabo' },
    { name: 'Bata', slug: 'bata' },
    { name: 'Ebebiyin', slug: 'ebebiyin' },
    { name: 'Mongomo', slug: 'mongomo' },
  ],
  er: [
    { name: 'Asmara', slug: 'asmara' },
    { name: 'Massawa', slug: 'massawa' },
    { name: 'Keren', slug: 'keren' },
    { name: 'Assab', slug: 'assab' },
  ],
  ee: [
    { name: 'Tallinn', slug: 'tallinn' },
    { name: 'Tartu', slug: 'tartu' },
    { name: 'Pärnu', slug: 'parnu' },
    { name: 'Narva', slug: 'narva' },
    { name: 'Saaremaa', slug: 'saaremaa' },
    { name: 'Haapsalu', slug: 'haapsalu' },
  ],
  sz: [
    { name: 'Mbabane', slug: 'mbabane' },
    { name: 'Manzini', slug: 'manzini' },
    { name: 'Lobamba', slug: 'lobamba' },
    { name: 'Ezulwini', slug: 'ezulwini' },
  ],
  et: [
    { name: 'Addis Ababa', slug: 'addis-ababa' },
    { name: 'Lalibela', slug: 'lalibela' },
    { name: 'Gondar', slug: 'gondar' },
    { name: 'Axum', slug: 'axum' },
    { name: 'Bahir Dar', slug: 'bahir-dar' },
    { name: 'Dire Dawa', slug: 'dire-dawa' },
    { name: 'Mekelle', slug: 'mekelle' },
  ],
  fk: [
    { name: 'Stanley', slug: 'stanley' },
    { name: 'Goose Green', slug: 'goose-green' },
    { name: 'Port Howard', slug: 'port-howard' },
  ],
  fo: [
    { name: 'Tórshavn', slug: 'torshavn' },
    { name: 'Klaksvík', slug: 'klaksvik' },
    { name: 'Runavík', slug: 'runavik' },
    { name: 'Vágur', slug: 'vagur' },
  ],
  fj: [
    { name: 'Nadi', slug: 'nadi' },
    { name: 'Suva', slug: 'suva' },
    { name: 'Denarau Island', slug: 'denarau-island' },
    { name: 'Coral Coast', slug: 'coral-coast' },
    { name: 'Mamanuca Islands', slug: 'mamanuca-islands' },
    { name: 'Yasawa Islands', slug: 'yasawa-islands' },
    { name: 'Savusavu', slug: 'savusavu' },
  ],
  fi: [
    { name: 'Helsinki', slug: 'helsinki' },
    { name: 'Rovaniemi', slug: 'rovaniemi' },
    { name: 'Turku', slug: 'turku' },
    { name: 'Tampere', slug: 'tampere' },
    { name: 'Oulu', slug: 'oulu' },
    { name: 'Levi', slug: 'levi' },
    { name: 'Saariselkä', slug: 'saariselka' },
  ],
  fr: [
    { name: 'Paris', slug: 'paris' },
    { name: 'Nice', slug: 'nice' },
    { name: 'Lyon', slug: 'lyon' },
    { name: 'Marseille', slug: 'marseille' },
    { name: 'Bordeaux', slug: 'bordeaux' },
    { name: 'Toulouse', slug: 'toulouse' },
    { name: 'Strasbourg', slug: 'strasbourg' },
    { name: 'Nantes', slug: 'nantes' },
    { name: 'Cannes', slug: 'cannes' },
    { name: 'Monaco', slug: 'monaco' },
    { name: 'Mont-Saint-Michel', slug: 'mont-saint-michel' },
    { name: 'Versailles', slug: 'versailles' },
    { name: 'Chamonix', slug: 'chamonix' },
  ],
  pf: [
    { name: 'Papeete', slug: 'papeete' },
    { name: 'Bora Bora', slug: 'bora-bora' },
    { name: 'Moorea', slug: 'moorea' },
    { name: 'Tahiti', slug: 'tahiti' },
    { name: 'Rangiroa', slug: 'rangiroa' },
    { name: 'Huahine', slug: 'huahine' },
  ],
  ga: [
    { name: 'Libreville', slug: 'libreville' },
    { name: 'Port-Gentil', slug: 'port-gentil' },
    { name: 'Franceville', slug: 'franceville' },
    { name: 'Lambaréné', slug: 'lambarene' },
  ],
  gm: [
    { name: 'Banjul', slug: 'banjul' },
    { name: 'Serrekunda', slug: 'serrekunda' },
    { name: 'Kotu', slug: 'kotu' },
    { name: 'Kololi', slug: 'kololi' },
    { name: 'Bakau', slug: 'bakau' },
  ],
  ge: [
    { name: 'Tbilisi', slug: 'tbilisi' },
    { name: 'Batumi', slug: 'batumi' },
    { name: 'Kutaisi', slug: 'kutaisi' },
    { name: 'Gudauri', slug: 'gudauri' },
    { name: 'Mestia', slug: 'mestia' },
    { name: 'Mtskheta', slug: 'mtskheta' },
    { name: 'Kazbegi', slug: 'kazbegi' },
    { name: 'Borjomi', slug: 'borjomi' },
  ],
  gh: [
    { name: 'Accra', slug: 'accra' },
    { name: 'Kumasi', slug: 'kumasi' },
    { name: 'Cape Coast', slug: 'cape-coast' },
    { name: 'Takoradi', slug: 'takoradi' },
    { name: 'Tamale', slug: 'tamale' },
    { name: 'Ho', slug: 'ho' },
  ],
  gi: [
    { name: 'Gibraltar', slug: 'gibraltar' },
    { name: 'Catalan Bay', slug: 'catalan-bay' },
    { name: 'Europa Point', slug: 'europa-point' },
  ],
  gl: [
    { name: 'Nuuk', slug: 'nuuk' },
    { name: 'Ilulissat', slug: 'ilulissat' },
    { name: 'Sisimiut', slug: 'sisimiut' },
    { name: 'Qaqortoq', slug: 'qaqortoq' },
    { name: 'Tasiilaq', slug: 'tasiilaq' },
  ],
  gd: [
    { name: "St. George's", slug: 'st-georges' },
    { name: 'Grand Anse', slug: 'grand-anse' },
    { name: 'Gouyave', slug: 'gouyave' },
    { name: 'Carriacou', slug: 'carriacou' },
  ],
  gr: [
    { name: 'Athens', slug: 'athens' },
    { name: 'Santorini', slug: 'santorini' },
    { name: 'Mykonos', slug: 'mykonos' },
    { name: 'Crete', slug: 'crete' },
    { name: 'Rhodes', slug: 'rhodes' },
    { name: 'Corfu', slug: 'corfu' },
    { name: 'Thessaloniki', slug: 'thessaloniki' },
    { name: 'Naxos', slug: 'naxos' },
    { name: 'Paros', slug: 'paros' },
    { name: 'Zakynthos', slug: 'zakynthos' },
    { name: 'Meteora', slug: 'meteora' },
  ],
  gt: [
    { name: 'Guatemala City', slug: 'guatemala-city' },
    { name: 'Antigua', slug: 'antigua' },
    { name: 'Lake Atitlán', slug: 'lake-atitlan' },
    { name: 'Flores', slug: 'flores' },
    { name: 'Quetzaltenango', slug: 'quetzaltenango' },
    { name: 'Tikal', slug: 'tikal' },
  ],
  gn: [
    { name: 'Conakry', slug: 'conakry' },
    { name: 'Kankan', slug: 'kankan' },
    { name: 'Labé', slug: 'labe' },
    { name: 'Nzérékoré', slug: 'nzerekore' },
  ],
  gw: [
    { name: 'Bissau', slug: 'bissau' },
    { name: 'Bafatá', slug: 'bafata' },
    { name: 'Gabú', slug: 'gabu' },
    { name: 'Bolama', slug: 'bolama' },
  ],
  gy: [
    { name: 'Georgetown', slug: 'georgetown' },
    { name: 'Linden', slug: 'linden' },
    { name: 'New Amsterdam', slug: 'new-amsterdam' },
    { name: 'Lethem', slug: 'lethem' },
  ],
  ht: [
    { name: 'Port-au-Prince', slug: 'port-au-prince' },
    { name: 'Cap-Haïtien', slug: 'cap-haitien' },
    { name: 'Jacmel', slug: 'jacmel' },
    { name: 'Labadee', slug: 'labadee' },
    { name: 'Les Cayes', slug: 'les-cayes' },
  ],
  hn: [
    { name: 'Tegucigalpa', slug: 'tegucigalpa' },
    { name: 'San Pedro Sula', slug: 'san-pedro-sula' },
    { name: 'Roatán', slug: 'roatan' },
    { name: 'La Ceiba', slug: 'la-ceiba' },
    { name: 'Copán', slug: 'copan' },
    { name: 'Utila', slug: 'utila' },
  ],
  hu: [
    { name: 'Budapest', slug: 'budapest' },
    { name: 'Debrecen', slug: 'debrecen' },
    { name: 'Szeged', slug: 'szeged' },
    { name: 'Pécs', slug: 'pecs' },
    { name: 'Eger', slug: 'eger' },
    { name: 'Lake Balaton', slug: 'lake-balaton' },
    { name: 'Győr', slug: 'gyor' },
  ],
  is: [
    { name: 'Reykjavik', slug: 'reykjavik' },
    { name: 'Akureyri', slug: 'akureyri' },
    { name: 'Vík', slug: 'vik' },
    { name: 'Höfn', slug: 'hofn' },
    { name: 'Selfoss', slug: 'selfoss' },
    { name: 'Ísafjörður', slug: 'isafjordur' },
    { name: 'Keflavík', slug: 'keflavik' },
  ],
  in: [
    { name: 'New Delhi', slug: 'new-delhi' },
    { name: 'Mumbai', slug: 'mumbai' },
    { name: 'Agra', slug: 'agra' },
    { name: 'Jaipur', slug: 'jaipur' },
    { name: 'Goa', slug: 'goa' },
    { name: 'Varanasi', slug: 'varanasi' },
    { name: 'Kolkata', slug: 'kolkata' },
    { name: 'Bangalore', slug: 'bangalore' },
    { name: 'Chennai', slug: 'chennai' },
    { name: 'Hyderabad', slug: 'hyderabad' },
    { name: 'Kerala', slug: 'kerala' },
    { name: 'Amritsar', slug: 'amritsar' },
    { name: 'Udaipur', slug: 'udaipur' },
    { name: 'Darjeeling', slug: 'darjeeling' },
    { name: 'Rishikesh', slug: 'rishikesh' },
  ],
  id: [
    { name: 'Bali', slug: 'bali' },
    { name: 'Jakarta', slug: 'jakarta' },
    { name: 'Yogyakarta', slug: 'yogyakarta' },
    { name: 'Lombok', slug: 'lombok' },
    { name: 'Surabaya', slug: 'surabaya' },
    { name: 'Medan', slug: 'medan' },
    { name: 'Makassar', slug: 'makassar' },
    { name: 'Komodo', slug: 'komodo' },
    { name: 'Raja Ampat', slug: 'raja-ampat' },
    { name: 'Flores', slug: 'flores' },
  ],
  ir: [
    { name: 'Tehran', slug: 'tehran' },
    { name: 'Mashhad', slug: 'mashhad' },
    { name: 'Isfahan', slug: 'isfahan' },
    { name: 'Shiraz', slug: 'shiraz' },
    { name: 'Tabriz', slug: 'tabriz' },
    { name: 'Yazd', slug: 'yazd' },
    { name: 'Kashan', slug: 'kashan' },
    { name: 'Qom', slug: 'qom' },
    { name: 'Ahvaz', slug: 'ahvaz' },
    { name: 'Hamadan', slug: 'hamadan' },
    { name: 'Rasht', slug: 'rasht' },
  ],
  iq: [
    { name: 'Baghdad', slug: 'baghdad' },
    { name: 'Basra', slug: 'basra' },
    { name: 'Najaf', slug: 'najaf' },
    { name: 'Karbala', slug: 'karbala' },
    { name: 'Erbil', slug: 'erbil' },
    { name: 'Sulaymaniyah', slug: 'sulaymaniyah' },
    { name: 'Mosul', slug: 'mosul' },
    { name: 'Kirkuk', slug: 'kirkuk' },
    { name: 'Samarra', slug: 'samarra' },
    { name: 'Babylon', slug: 'babylon' },
  ],
  ie: [
    { name: 'Dublin', slug: 'dublin' },
    { name: 'Galway', slug: 'galway' },
    { name: 'Cork', slug: 'cork' },
    { name: 'Killarney', slug: 'killarney' },
    { name: 'Limerick', slug: 'limerick' },
    { name: 'Kilkenny', slug: 'kilkenny' },
    { name: 'Waterford', slug: 'waterford' },
    { name: 'Dingle', slug: 'dingle' },
  ],
  im: [
    { name: 'Douglas', slug: 'douglas' },
    { name: 'Ramsey', slug: 'ramsey' },
    { name: 'Peel', slug: 'peel' },
    { name: 'Castletown', slug: 'castletown' },
  ],
  il: [
    { name: 'Jerusalem', slug: 'jerusalem' },
    { name: 'Tel Aviv', slug: 'tel-aviv' },
    { name: 'Haifa', slug: 'haifa' },
    { name: 'Eilat', slug: 'eilat' },
    { name: 'Nazareth', slug: 'nazareth' },
    { name: 'Tiberias', slug: 'tiberias' },
    { name: 'Dead Sea', slug: 'dead-sea' },
    { name: 'Netanya', slug: 'netanya' },
  ],
  it: [
    { name: 'Rome', slug: 'rome' },
    { name: 'Venice', slug: 'venice' },
    { name: 'Florence', slug: 'florence' },
    { name: 'Milan', slug: 'milan' },
    { name: 'Naples', slug: 'naples' },
    { name: 'Amalfi', slug: 'amalfi' },
    { name: 'Positano', slug: 'positano' },
    { name: 'Sicily', slug: 'sicily' },
    { name: 'Bologna', slug: 'bologna' },
    { name: 'Turin', slug: 'turin' },
    { name: 'Verona', slug: 'verona' },
    { name: 'Pisa', slug: 'pisa' },
    { name: 'Capri', slug: 'capri' },
    { name: 'Sardinia', slug: 'sardinia' },
  ],
  jm: [
    { name: 'Kingston', slug: 'kingston' },
    { name: 'Montego Bay', slug: 'montego-bay' },
    { name: 'Negril', slug: 'negril' },
    { name: 'Ocho Rios', slug: 'ocho-rios' },
    { name: 'Port Antonio', slug: 'port-antonio' },
    { name: 'Runaway Bay', slug: 'runaway-bay' },
  ],
  jp: [
    { name: 'Tokyo', slug: 'tokyo' },
    { name: 'Osaka', slug: 'osaka' },
    { name: 'Kyoto', slug: 'kyoto' },
    { name: 'Hiroshima', slug: 'hiroshima' },
    { name: 'Sapporo', slug: 'sapporo' },
    { name: 'Fukuoka', slug: 'fukuoka' },
    { name: 'Nara', slug: 'nara' },
    { name: 'Yokohama', slug: 'yokohama' },
    { name: 'Nagoya', slug: 'nagoya' },
    { name: 'Kobe', slug: 'kobe' },
    { name: 'Nikko', slug: 'nikko' },
    { name: 'Hakone', slug: 'hakone' },
  ],
  jo: [
    { name: 'Amman', slug: 'amman' },
    { name: 'Petra', slug: 'petra' },
    { name: 'Aqaba', slug: 'aqaba' },
    { name: 'Wadi Rum', slug: 'wadi-rum' },
    { name: 'Jerash', slug: 'jerash' },
    { name: 'Madaba', slug: 'madaba' },
    { name: 'Dead Sea', slug: 'dead-sea' },
    { name: 'Irbid', slug: 'irbid' },
    { name: 'Zarqa', slug: 'zarqa' },
  ],
  kz: [
    { name: 'Almaty', slug: 'almaty' },
    { name: 'Nur-Sultan', slug: 'nur-sultan' },
    { name: 'Shymkent', slug: 'shymkent' },
    { name: 'Aktau', slug: 'aktau' },
    { name: 'Semey', slug: 'semey' },
    { name: 'Pavlodar', slug: 'pavlodar' },
  ],
  ke: [
    { name: 'Nairobi', slug: 'nairobi' },
    { name: 'Mombasa', slug: 'mombasa' },
    { name: 'Maasai Mara', slug: 'maasai-mara' },
    { name: 'Amboseli', slug: 'amboseli' },
    { name: 'Lamu', slug: 'lamu' },
    { name: 'Malindi', slug: 'malindi' },
    { name: 'Diani', slug: 'diani' },
    { name: 'Kisumu', slug: 'kisumu' },
    { name: 'Nanyuki', slug: 'nanyuki' },
    { name: 'Nakuru', slug: 'nakuru' },
  ],
  ki: [
    { name: 'Tarawa', slug: 'tarawa' },
    { name: 'Betio', slug: 'betio' },
    { name: 'Kiritimati', slug: 'kiritimati' },
  ],
  xk: [
    { name: 'Pristina', slug: 'pristina' },
    { name: 'Prizren', slug: 'prizren' },
    { name: 'Peja', slug: 'peja' },
    { name: 'Gjakova', slug: 'gjakova' },
    { name: 'Mitrovica', slug: 'mitrovica' },
  ],
  kw: [
    { name: 'Kuwait City', slug: 'kuwait-city' },
    { name: 'Salmiya', slug: 'salmiya' },
    { name: 'Hawalli', slug: 'hawalli' },
    { name: 'Jahra', slug: 'jahra' },
    { name: 'Fahaheel', slug: 'fahaheel' },
  ],
  kg: [
    { name: 'Bishkek', slug: 'bishkek' },
    { name: 'Osh', slug: 'osh' },
    { name: 'Karakol', slug: 'karakol' },
    { name: 'Cholpon-Ata', slug: 'cholpon-ata' },
    { name: 'Naryn', slug: 'naryn' },
    { name: 'Jalal-Abad', slug: 'jalal-abad' },
  ],
  la: [
    { name: 'Vientiane', slug: 'vientiane' },
    { name: 'Luang Prabang', slug: 'luang-prabang' },
    { name: 'Vang Vieng', slug: 'vang-vieng' },
    { name: 'Pakse', slug: 'pakse' },
    { name: 'Savannakhet', slug: 'savannakhet' },
    { name: 'Phonsavan', slug: 'phonsavan' },
  ],
  lv: [
    { name: 'Riga', slug: 'riga' },
    { name: 'Jurmala', slug: 'jurmala' },
    { name: 'Liepāja', slug: 'liepaja' },
    { name: 'Daugavpils', slug: 'daugavpils' },
    { name: 'Sigulda', slug: 'sigulda' },
    { name: 'Cēsis', slug: 'cesis' },
  ],
  lb: [
    { name: 'Beirut', slug: 'beirut' },
    { name: 'Byblos', slug: 'byblos' },
    { name: 'Baalbek', slug: 'baalbek' },
    { name: 'Tripoli', slug: 'tripoli' },
    { name: 'Sidon', slug: 'sidon' },
    { name: 'Tyre', slug: 'tyre' },
    { name: 'Jounieh', slug: 'jounieh' },
  ],
  lc: [
    { name: 'Castries', slug: 'castries' },
    { name: 'Rodney Bay', slug: 'rodney-bay' },
    { name: 'Soufrière', slug: 'soufriere' },
    { name: 'Gros Islet', slug: 'gros-islet' },
    { name: 'Marigot Bay', slug: 'marigot-bay' },
  ],
  li: [
    { name: 'Vaduz', slug: 'vaduz' },
    { name: 'Schaan', slug: 'schaan' },
    { name: 'Balzers', slug: 'balzers' },
    { name: 'Triesenberg', slug: 'triesenberg' },
  ],
  lk: [
    { name: 'Colombo', slug: 'colombo' },
    { name: 'Kandy', slug: 'kandy' },
    { name: 'Galle', slug: 'galle' },
    { name: 'Negombo', slug: 'negombo' },
    { name: 'Ella', slug: 'ella' },
    { name: 'Nuwara Eliya', slug: 'nuwara-eliya' },
    { name: 'Sigiriya', slug: 'sigiriya' },
    { name: 'Mirissa', slug: 'mirissa' },
    { name: 'Bentota', slug: 'bentota' },
    { name: 'Trincomalee', slug: 'trincomalee' },
  ],
  lr: [
    { name: 'Monrovia', slug: 'monrovia' },
    { name: 'Gbarnga', slug: 'gbarnga' },
    { name: 'Buchanan', slug: 'buchanan' },
    { name: 'Harper', slug: 'harper' },
  ],
  ls: [
    { name: 'Maseru', slug: 'maseru' },
    { name: 'Teyateyaneng', slug: 'teyateyaneng' },
    { name: 'Leribe', slug: 'leribe' },
    { name: 'Mafeteng', slug: 'mafeteng' },
  ],
  lt: [
    { name: 'Vilnius', slug: 'vilnius' },
    { name: 'Kaunas', slug: 'kaunas' },
    { name: 'Klaipėda', slug: 'klaipeda' },
    { name: 'Palanga', slug: 'palanga' },
    { name: 'Trakai', slug: 'trakai' },
    { name: 'Nida', slug: 'nida' },
  ],
  lu: [
    { name: 'Luxembourg City', slug: 'luxembourg-city' },
    { name: 'Esch-sur-Alzette', slug: 'esch-sur-alzette' },
    { name: 'Differdange', slug: 'differdange' },
    { name: 'Echternach', slug: 'echternach' },
    { name: 'Vianden', slug: 'vianden' },
  ],
  mo: [
    { name: 'Macau', slug: 'macau' },
    { name: 'Taipa', slug: 'taipa' },
    { name: 'Coloane', slug: 'coloane' },
    { name: 'Cotai', slug: 'cotai' },
  ],
  mg: [
    { name: 'Antananarivo', slug: 'antananarivo' },
    { name: 'Nosy Be', slug: 'nosy-be' },
    { name: 'Toamasina', slug: 'toamasina' },
    { name: 'Antsirabe', slug: 'antsirabe' },
    { name: 'Morondava', slug: 'morondava' },
    { name: 'Diego Suarez', slug: 'diego-suarez' },
  ],
  mw: [
    { name: 'Lilongwe', slug: 'lilongwe' },
    { name: 'Blantyre', slug: 'blantyre' },
    { name: 'Mzuzu', slug: 'mzuzu' },
    { name: 'Zomba', slug: 'zomba' },
    { name: 'Cape Maclear', slug: 'cape-maclear' },
  ],
  my: [
    { name: 'Kuala Lumpur', slug: 'kuala-lumpur' },
    { name: 'Penang', slug: 'penang' },
    { name: 'Langkawi', slug: 'langkawi' },
    { name: 'Kota Kinabalu', slug: 'kota-kinabalu' },
    { name: 'Malacca', slug: 'malacca' },
    { name: 'Johor Bahru', slug: 'johor-bahru' },
    { name: 'Cameron Highlands', slug: 'cameron-highlands' },
    { name: 'Ipoh', slug: 'ipoh' },
  ],
  mv: [
    { name: 'Malé', slug: 'male' },
    { name: 'Maafushi', slug: 'maafushi' },
    { name: 'Hulhumalé', slug: 'hulhumale' },
    { name: 'Ari Atoll', slug: 'ari-atoll' },
    { name: 'Baa Atoll', slug: 'baa-atoll' },
    { name: 'North Malé Atoll', slug: 'north-male-atoll' },
    { name: 'South Malé Atoll', slug: 'south-male-atoll' },
  ],
  ml: [
    { name: 'Bamako', slug: 'bamako' },
    { name: 'Timbuktu', slug: 'timbuktu' },
    { name: 'Mopti', slug: 'mopti' },
    { name: 'Ségou', slug: 'segou' },
    { name: 'Gao', slug: 'gao' },
  ],
  mt: [
    { name: 'Valletta', slug: 'valletta' },
    { name: 'Sliema', slug: 'sliema' },
    { name: "St. Julian's", slug: 'st-julians' },
    { name: 'Mdina', slug: 'mdina' },
    { name: 'Gozo', slug: 'gozo' },
    { name: 'Marsaxlokk', slug: 'marsaxlokk' },
    { name: 'Mellieħa', slug: 'mellieha' },
  ],
  mr: [
    { name: 'Nouakchott', slug: 'nouakchott' },
    { name: 'Nouadhibou', slug: 'nouadhibou' },
    { name: 'Atar', slug: 'atar' },
    { name: 'Chinguetti', slug: 'chinguetti' },
  ],
  mu: [
    { name: 'Port Louis', slug: 'port-louis' },
    { name: 'Grand Baie', slug: 'grand-baie' },
    { name: 'Flic en Flac', slug: 'flic-en-flac' },
    { name: 'Belle Mare', slug: 'belle-mare' },
    { name: 'Le Morne', slug: 'le-morne' },
    { name: 'Trou aux Biches', slug: 'trou-aux-biches' },
    { name: 'Mahébourg', slug: 'mahebourg' },
  ],
  mx: [
    { name: 'Mexico City', slug: 'mexico-city' },
    { name: 'Cancun', slug: 'cancun' },
    { name: 'Playa del Carmen', slug: 'playa-del-carmen' },
    { name: 'Cabo San Lucas', slug: 'cabo-san-lucas' },
    { name: 'Guadalajara', slug: 'guadalajara' },
    { name: 'Oaxaca', slug: 'oaxaca' },
    { name: 'San Miguel de Allende', slug: 'san-miguel-de-allende' },
    { name: 'Puerto Vallarta', slug: 'puerto-vallarta' },
    { name: 'Mérida', slug: 'merida' },
    { name: 'Tulum', slug: 'tulum' },
  ],
  fm: [
    { name: 'Palikir', slug: 'palikir' },
    { name: 'Weno', slug: 'weno' },
    { name: 'Kolonia', slug: 'kolonia' },
    { name: 'Tofol', slug: 'tofol' },
  ],
  md: [
    { name: 'Chișinău', slug: 'chisinau' },
    { name: 'Bălți', slug: 'balti' },
    { name: 'Tiraspol', slug: 'tiraspol' },
    { name: 'Orhei', slug: 'orhei' },
    { name: 'Cahul', slug: 'cahul' },
  ],
  mc: [
    { name: 'Monaco', slug: 'monaco' },
    { name: 'Monte Carlo', slug: 'monte-carlo' },
    { name: 'La Condamine', slug: 'la-condamine' },
    { name: 'Fontvieille', slug: 'fontvieille' },
  ],
  mn: [
    { name: 'Ulaanbaatar', slug: 'ulaanbaatar' },
    { name: 'Erdenet', slug: 'erdenet' },
    { name: 'Darkhan', slug: 'darkhan' },
    { name: 'Kharkhorin', slug: 'kharkhorin' },
    { name: 'Ölgii', slug: 'olgii' },
  ],
  me: [
    { name: 'Podgorica', slug: 'podgorica' },
    { name: 'Budva', slug: 'budva' },
    { name: 'Kotor', slug: 'kotor' },
    { name: 'Herceg Novi', slug: 'herceg-novi' },
    { name: 'Tivat', slug: 'tivat' },
    { name: 'Bar', slug: 'bar' },
    { name: 'Ulcinj', slug: 'ulcinj' },
    { name: 'Cetinje', slug: 'cetinje' },
  ],
  ms: [
    { name: 'Brades', slug: 'brades' },
    { name: 'Little Bay', slug: 'little-bay' },
    { name: 'Salem', slug: 'salem' },
  ],
  ma: [
    { name: 'Marrakech', slug: 'marrakech' },
    { name: 'Casablanca', slug: 'casablanca' },
    { name: 'Fes', slug: 'fes' },
    { name: 'Tangier', slug: 'tangier' },
    { name: 'Chefchaouen', slug: 'chefchaouen' },
    { name: 'Essaouira', slug: 'essaouira' },
    { name: 'Agadir', slug: 'agadir' },
    { name: 'Rabat', slug: 'rabat' },
    { name: 'Meknes', slug: 'meknes' },
    { name: 'Merzouga', slug: 'merzouga' },
  ],
  mz: [
    { name: 'Maputo', slug: 'maputo' },
    { name: 'Beira', slug: 'beira' },
    { name: 'Nampula', slug: 'nampula' },
    { name: 'Pemba', slug: 'pemba' },
    { name: 'Inhambane', slug: 'inhambane' },
    { name: 'Vilanculos', slug: 'vilanculos' },
  ],
  mm: [
    { name: 'Yangon', slug: 'yangon' },
    { name: 'Mandalay', slug: 'mandalay' },
    { name: 'Bagan', slug: 'bagan' },
    { name: 'Inle Lake', slug: 'inle-lake' },
    { name: 'Naypyidaw', slug: 'naypyidaw' },
    { name: 'Ngapali', slug: 'ngapali' },
  ],
  na: [
    { name: 'Windhoek', slug: 'windhoek' },
    { name: 'Swakopmund', slug: 'swakopmund' },
    { name: 'Walvis Bay', slug: 'walvis-bay' },
    { name: 'Etosha', slug: 'etosha' },
    { name: 'Sossusvlei', slug: 'sossusvlei' },
    { name: 'Lüderitz', slug: 'luderitz' },
  ],
  nc: [
    { name: 'Nouméa', slug: 'noumea' },
    { name: 'Mont-Dore', slug: 'mont-dore' },
    { name: 'Dumbéa', slug: 'dumbea' },
    { name: 'Île des Pins', slug: 'ile-des-pins' },
  ],
  ne: [
    { name: 'Niamey', slug: 'niamey' },
    { name: 'Zinder', slug: 'zinder' },
    { name: 'Maradi', slug: 'maradi' },
    { name: 'Agadez', slug: 'agadez' },
  ],
  ng: [
    { name: 'Lagos', slug: 'lagos' },
    { name: 'Abuja', slug: 'abuja' },
    { name: 'Kano', slug: 'kano' },
    { name: 'Ibadan', slug: 'ibadan' },
    { name: 'Port Harcourt', slug: 'port-harcourt' },
    { name: 'Benin City', slug: 'benin-city' },
    { name: 'Enugu', slug: 'enugu' },
    { name: 'Calabar', slug: 'calabar' },
    { name: 'Jos', slug: 'jos' },
  ],
  ni: [
    { name: 'Managua', slug: 'managua' },
    { name: 'Granada', slug: 'granada' },
    { name: 'León', slug: 'leon' },
    { name: 'San Juan del Sur', slug: 'san-juan-del-sur' },
    { name: 'Ometepe', slug: 'ometepe' },
    { name: 'Masaya', slug: 'masaya' },
  ],
  nl: [
    { name: 'Amsterdam', slug: 'amsterdam' },
    { name: 'Rotterdam', slug: 'rotterdam' },
    { name: 'The Hague', slug: 'the-hague' },
    { name: 'Utrecht', slug: 'utrecht' },
    { name: 'Eindhoven', slug: 'eindhoven' },
    { name: 'Maastricht', slug: 'maastricht' },
    { name: 'Haarlem', slug: 'haarlem' },
    { name: 'Delft', slug: 'delft' },
    { name: 'Groningen', slug: 'groningen' },
  ],
  no: [
    { name: 'Oslo', slug: 'oslo' },
    { name: 'Bergen', slug: 'bergen' },
    { name: 'Tromsø', slug: 'tromso' },
    { name: 'Stavanger', slug: 'stavanger' },
    { name: 'Trondheim', slug: 'trondheim' },
    { name: 'Ålesund', slug: 'alesund' },
    { name: 'Lofoten', slug: 'lofoten' },
    { name: 'Geiranger', slug: 'geiranger' },
  ],
  np: [
    { name: 'Kathmandu', slug: 'kathmandu' },
    { name: 'Pokhara', slug: 'pokhara' },
    { name: 'Chitwan', slug: 'chitwan' },
    { name: 'Lumbini', slug: 'lumbini' },
    { name: 'Bhaktapur', slug: 'bhaktapur' },
    { name: 'Nagarkot', slug: 'nagarkot' },
    { name: 'Namche Bazaar', slug: 'namche-bazaar' },
  ],
  nr: [
    { name: 'Yaren', slug: 'yaren' },
    { name: 'Denigomodu', slug: 'denigomodu' },
    { name: 'Meneng', slug: 'meneng' },
  ],
  nu: [
    { name: 'Alofi', slug: 'alofi' },
    { name: 'Avatele', slug: 'avatele' },
    { name: 'Hakupu', slug: 'hakupu' },
  ],
  nz: [
    { name: 'Auckland', slug: 'auckland' },
    { name: 'Wellington', slug: 'wellington' },
    { name: 'Queenstown', slug: 'queenstown' },
    { name: 'Christchurch', slug: 'christchurch' },
    { name: 'Rotorua', slug: 'rotorua' },
    { name: 'Taupo', slug: 'taupo' },
    { name: 'Dunedin', slug: 'dunedin' },
    { name: 'Hamilton', slug: 'hamilton' },
    { name: 'Napier', slug: 'napier' },
    { name: 'Tauranga', slug: 'tauranga' },
  ],
  om: [
    { name: 'Muscat', slug: 'muscat' },
    { name: 'Salalah', slug: 'salalah' },
    { name: 'Nizwa', slug: 'nizwa' },
    { name: 'Sohar', slug: 'sohar' },
    { name: 'Sur', slug: 'sur' },
    { name: 'Khasab', slug: 'khasab' },
    { name: 'Wahiba Sands', slug: 'wahiba-sands' },
  ],
  pk: [
    { name: 'Lahore', slug: 'lahore' },
    { name: 'Islamabad', slug: 'islamabad' },
    { name: 'Karachi', slug: 'karachi' },
    { name: 'Rawalpindi', slug: 'rawalpindi' },
    { name: 'Murree', slug: 'murree' },
    { name: 'Naran', slug: 'naran' },
    { name: 'Skardu', slug: 'skardu' },
    { name: 'Gilgit', slug: 'gilgit' },
    { name: 'Peshawar', slug: 'peshawar' },
    { name: 'Quetta', slug: 'quetta' },
    { name: 'Multan', slug: 'multan' },
    { name: 'Faisalabad', slug: 'faisalabad' },
    { name: 'Hyderabad', slug: 'hyderabad' },
    { name: 'Sialkot', slug: 'sialkot' },
    { name: 'Gujranwala', slug: 'gujranwala' },
    { name: 'Abbottabad', slug: 'abbottabad' },
    { name: 'Muzaffarabad', slug: 'muzaffarabad' },
    { name: 'Chitral', slug: 'chitral' },
    { name: 'Gwadar', slug: 'gwadar' },
    { name: 'Bahawalpur', slug: 'bahawalpur' },
    { name: 'Sukkur', slug: 'sukkur' },
    { name: 'Karimabad', slug: 'karimabad' },
    { name: 'Shigar', slug: 'shigar' },
    { name: 'Mansehra', slug: 'mansehra' },
    { name: 'Mardan', slug: 'mardan' },
  ],
  pw: [
    { name: 'Ngerulmud', slug: 'ngerulmud' },
    { name: 'Koror', slug: 'koror' },
    { name: 'Airai', slug: 'airai' },
    { name: 'Peleliu', slug: 'peleliu' },
  ],
  ps: [
    { name: 'Ramallah', slug: 'ramallah' },
    { name: 'Bethlehem', slug: 'bethlehem' },
    { name: 'Hebron', slug: 'hebron' },
    { name: 'Nablus', slug: 'nablus' },
    { name: 'Jericho', slug: 'jericho' },
    { name: 'Gaza', slug: 'gaza' },
  ],
  pa: [
    { name: 'Panama City', slug: 'panama-city' },
    { name: 'Bocas del Toro', slug: 'bocas-del-toro' },
    { name: 'Boquete', slug: 'boquete' },
    { name: 'San Blas Islands', slug: 'san-blas-islands' },
    { name: 'David', slug: 'david' },
    { name: 'Colón', slug: 'colon' },
  ],
  pg: [
    { name: 'Port Moresby', slug: 'port-moresby' },
    { name: 'Lae', slug: 'lae' },
    { name: 'Madang', slug: 'madang' },
    { name: 'Mount Hagen', slug: 'mount-hagen' },
    { name: 'Rabaul', slug: 'rabaul' },
  ],
  py: [
    { name: 'Asunción', slug: 'asuncion' },
    { name: 'Ciudad del Este', slug: 'ciudad-del-este' },
    { name: 'Encarnación', slug: 'encarnacion' },
    { name: 'Pedro Juan Caballero', slug: 'pedro-juan-caballero' },
    { name: 'Villarrica', slug: 'villarrica' },
  ],
  pe: [
    { name: 'Lima', slug: 'lima' },
    { name: 'Cusco', slug: 'cusco' },
    { name: 'Arequipa', slug: 'arequipa' },
    { name: 'Machu Picchu', slug: 'machu-picchu' },
    { name: 'Puno', slug: 'puno' },
    { name: 'Iquitos', slug: 'iquitos' },
    { name: 'Trujillo', slug: 'trujillo' },
    { name: 'Paracas', slug: 'paracas' },
    { name: 'Nazca', slug: 'nazca' },
  ],
  ph: [
    { name: 'Manila', slug: 'manila' },
    { name: 'Cebu', slug: 'cebu' },
    { name: 'Boracay', slug: 'boracay' },
    { name: 'Palawan', slug: 'palawan' },
    { name: 'Davao', slug: 'davao' },
    { name: 'Bohol', slug: 'bohol' },
    { name: 'Siargao', slug: 'siargao' },
    { name: 'El Nido', slug: 'el-nido' },
    { name: 'Coron', slug: 'coron' },
    { name: 'Baguio', slug: 'baguio' },
    { name: 'Tagaytay', slug: 'tagaytay' },
  ],
  pl: [
    { name: 'Warsaw', slug: 'warsaw' },
    { name: 'Krakow', slug: 'krakow' },
    { name: 'Gdańsk', slug: 'gdansk' },
    { name: 'Wrocław', slug: 'wroclaw' },
    { name: 'Poznań', slug: 'poznan' },
    { name: 'Zakopane', slug: 'zakopane' },
    { name: 'Łódź', slug: 'lodz' },
    { name: 'Katowice', slug: 'katowice' },
    { name: 'Lublin', slug: 'lublin' },
  ],
  pt: [
    { name: 'Lisbon', slug: 'lisbon' },
    { name: 'Porto', slug: 'porto' },
    { name: 'Algarve', slug: 'algarve' },
    { name: 'Madeira', slug: 'madeira' },
    { name: 'Azores', slug: 'azores' },
    { name: 'Sintra', slug: 'sintra' },
    { name: 'Coimbra', slug: 'coimbra' },
    { name: 'Faro', slug: 'faro' },
    { name: 'Braga', slug: 'braga' },
    { name: 'Évora', slug: 'evora' },
  ],
  pr: [
    { name: 'San Juan', slug: 'san-juan' },
    { name: 'Ponce', slug: 'ponce' },
    { name: 'Rincón', slug: 'rincon' },
    { name: 'Vieques', slug: 'vieques' },
    { name: 'Culebra', slug: 'culebra' },
    { name: 'Fajardo', slug: 'fajardo' },
  ],
  qa: [
    { name: 'Doha', slug: 'doha' },
    { name: 'Al Wakrah', slug: 'al-wakrah' },
    { name: 'Al Khor', slug: 'al-khor' },
    { name: 'Lusail', slug: 'lusail' },
    { name: 'The Pearl', slug: 'the-pearl' },
    { name: 'West Bay', slug: 'west-bay' },
  ],
  ro: [
    { name: 'Bucharest', slug: 'bucharest' },
    { name: 'Cluj-Napoca', slug: 'cluj-napoca' },
    { name: 'Brașov', slug: 'brasov' },
    { name: 'Sibiu', slug: 'sibiu' },
    { name: 'Timișoara', slug: 'timisoara' },
    { name: 'Constanța', slug: 'constanta' },
    { name: 'Sighișoara', slug: 'sighisoara' },
    { name: 'Iași', slug: 'iasi' },
  ],
  ru: [
    { name: 'Moscow', slug: 'moscow' },
    { name: 'Saint Petersburg', slug: 'saint-petersburg' },
    { name: 'Sochi', slug: 'sochi' },
    { name: 'Kazan', slug: 'kazan' },
    { name: 'Vladivostok', slug: 'vladivostok' },
    { name: 'Novosibirsk', slug: 'novosibirsk' },
    { name: 'Yekaterinburg', slug: 'yekaterinburg' },
    { name: 'Nizhny Novgorod', slug: 'nizhny-novgorod' },
    { name: 'Kaliningrad', slug: 'kaliningrad' },
    { name: 'Baikal', slug: 'baikal' },
  ],
  rw: [
    { name: 'Kigali', slug: 'kigali' },
    { name: 'Butare', slug: 'butare' },
    { name: 'Gisenyi', slug: 'gisenyi' },
    { name: 'Musanze', slug: 'musanze' },
    { name: 'Ruhengeri', slug: 'ruhengeri' },
    { name: 'Kibuye', slug: 'kibuye' },
  ],
  bl: [
    { name: 'Gustavia', slug: 'gustavia' },
    { name: 'Saint-Jean', slug: 'saint-jean' },
    { name: 'Lorient', slug: 'lorient' },
  ],
  sh: [
    { name: 'Jamestown', slug: 'jamestown' },
    { name: 'Longwood', slug: 'longwood' },
    { name: 'Half Tree Hollow', slug: 'half-tree-hollow' },
  ],
  kn: [
    { name: 'Basseterre', slug: 'basseterre' },
    { name: 'Charlestown', slug: 'charlestown' },
    { name: 'Frigate Bay', slug: 'frigate-bay' },
  ],
  mf: [
    { name: 'Marigot', slug: 'marigot' },
    { name: 'Grand Case', slug: 'grand-case' },
    { name: 'Orient Bay', slug: 'orient-bay' },
  ],
  pm: [
    { name: 'Saint-Pierre', slug: 'saint-pierre' },
    { name: 'Miquelon', slug: 'miquelon' },
  ],
  vc: [
    { name: 'Kingstown', slug: 'kingstown' },
    { name: 'Bequia', slug: 'bequia' },
    { name: 'Mustique', slug: 'mustique' },
    { name: 'Canouan', slug: 'canouan' },
    { name: 'Union Island', slug: 'union-island' },
  ],
  ws: [
    { name: 'Apia', slug: 'apia' },
    { name: 'Salelologa', slug: 'salelologa' },
    { name: 'Lalomanu', slug: 'lalomanu' },
    { name: 'Manase', slug: 'manase' },
  ],
  sm: [
    { name: 'San Marino', slug: 'san-marino' },
    { name: 'Borgo Maggiore', slug: 'borgo-maggiore' },
    { name: 'Serravalle', slug: 'serravalle' },
  ],
  st: [
    { name: 'São Tomé', slug: 'sao-tome' },
    { name: 'Santo António', slug: 'santo-antonio' },
    { name: 'Trindade', slug: 'trindade' },
  ],
  sa: [
    { name: 'Riyadh', slug: 'riyadh' },
    { name: 'Jeddah', slug: 'jeddah' },
    { name: 'Mecca', slug: 'mecca' },
    { name: 'Medina', slug: 'medina' },
    { name: 'Dammam', slug: 'dammam' },
    { name: 'Al Khobar', slug: 'al-khobar' },
    { name: 'Taif', slug: 'taif' },
    { name: 'Abha', slug: 'abha' },
    { name: 'Tabuk', slug: 'tabuk' },
    { name: 'Yanbu', slug: 'yanbu' },
    { name: 'Buraydah', slug: 'buraydah' },
    { name: 'Hail', slug: 'hail' },
    { name: 'Jizan', slug: 'jizan' },
    { name: 'Khamis Mushait', slug: 'khamis-mushait' },
    { name: 'Al Jubayl', slug: 'al-jubayl' },
    { name: 'Dhahran', slug: 'dhahran' },
    { name: 'Al Hofuf', slug: 'al-hofuf' },
    { name: 'Al Ula', slug: 'al-ula' },
    { name: 'Najran', slug: 'najran' },
    { name: 'Al Baha', slug: 'al-baha' },
  ],
  sn: [
    { name: 'Dakar', slug: 'dakar' },
    { name: 'Saint-Louis', slug: 'saint-louis' },
    { name: 'Thiès', slug: 'thies' },
    { name: 'Saly', slug: 'saly' },
    { name: 'Ziguinchor', slug: 'ziguinchor' },
    { name: 'Mbour', slug: 'mbour' },
  ],
  rs: [
    { name: 'Belgrade', slug: 'belgrade' },
    { name: 'Novi Sad', slug: 'novi-sad' },
    { name: 'Niš', slug: 'nis' },
    { name: 'Subotica', slug: 'subotica' },
    { name: 'Zlatibor', slug: 'zlatibor' },
    { name: 'Kopaonik', slug: 'kopaonik' },
    { name: 'Kragujevac', slug: 'kragujevac' },
  ],
  sc: [
    { name: 'Victoria', slug: 'victoria' },
    { name: 'Mahé', slug: 'mahe' },
    { name: 'Praslin', slug: 'praslin' },
    { name: 'La Digue', slug: 'la-digue' },
    { name: 'Beau Vallon', slug: 'beau-vallon' },
    { name: 'Anse Royale', slug: 'anse-royale' },
  ],
  sl: [
    { name: 'Freetown', slug: 'freetown' },
    { name: 'Bo', slug: 'bo' },
    { name: 'Kenema', slug: 'kenema' },
    { name: 'Makeni', slug: 'makeni' },
  ],
  sg: [
    { name: 'Singapore', slug: 'singapore' },
    { name: 'Marina Bay', slug: 'marina-bay' },
    { name: 'Sentosa', slug: 'sentosa' },
    { name: 'Orchard Road', slug: 'orchard-road' },
    { name: 'Chinatown', slug: 'chinatown' },
    { name: 'Little India', slug: 'little-india' },
  ],
  sx: [
    { name: 'Philipsburg', slug: 'philipsburg' },
    { name: 'Simpson Bay', slug: 'simpson-bay' },
    { name: 'Maho', slug: 'maho' },
    { name: 'Cupecoy', slug: 'cupecoy' },
  ],
  sk: [
    { name: 'Bratislava', slug: 'bratislava' },
    { name: 'Košice', slug: 'kosice' },
    { name: 'Žilina', slug: 'zilina' },
    { name: 'High Tatras', slug: 'high-tatras' },
    { name: 'Banská Bystrica', slug: 'banska-bystrica' },
    { name: 'Piešťany', slug: 'piestany' },
  ],
  si: [
    { name: 'Ljubljana', slug: 'ljubljana' },
    { name: 'Bled', slug: 'bled' },
    { name: 'Maribor', slug: 'maribor' },
    { name: 'Piran', slug: 'piran' },
    { name: 'Bohinj', slug: 'bohinj' },
    { name: 'Portorož', slug: 'portoroz' },
    { name: 'Kranjska Gora', slug: 'kranjska-gora' },
  ],
  sb: [
    { name: 'Honiara', slug: 'honiara' },
    { name: 'Gizo', slug: 'gizo' },
    { name: 'Auki', slug: 'auki' },
    { name: 'Munda', slug: 'munda' },
  ],
  za: [
    { name: 'Cape Town', slug: 'cape-town' },
    { name: 'Johannesburg', slug: 'johannesburg' },
    { name: 'Durban', slug: 'durban' },
    { name: 'Pretoria', slug: 'pretoria' },
    { name: 'Kruger', slug: 'kruger' },
    { name: 'Garden Route', slug: 'garden-route' },
    { name: 'Stellenbosch', slug: 'stellenbosch' },
    { name: 'Knysna', slug: 'knysna' },
    { name: 'Port Elizabeth', slug: 'port-elizabeth' },
    { name: 'East London', slug: 'east-london' },
  ],
  kr: [
    { name: 'Seoul', slug: 'seoul' },
    { name: 'Busan', slug: 'busan' },
    { name: 'Jeju', slug: 'jeju' },
    { name: 'Incheon', slug: 'incheon' },
    { name: 'Daegu', slug: 'daegu' },
    { name: 'Gyeongju', slug: 'gyeongju' },
    { name: 'Sokcho', slug: 'sokcho' },
    { name: 'Suwon', slug: 'suwon' },
    { name: 'Gwangju', slug: 'gwangju' },
  ],
  ss: [
    { name: 'Juba', slug: 'juba' },
    { name: 'Wau', slug: 'wau' },
    { name: 'Malakal', slug: 'malakal' },
    { name: 'Yambio', slug: 'yambio' },
  ],
  es: [
    { name: 'Madrid', slug: 'madrid' },
    { name: 'Barcelona', slug: 'barcelona' },
    { name: 'Seville', slug: 'seville' },
    { name: 'Valencia', slug: 'valencia' },
    { name: 'Granada', slug: 'granada' },
    { name: 'Malaga', slug: 'malaga' },
    { name: 'Bilbao', slug: 'bilbao' },
    { name: 'San Sebastian', slug: 'san-sebastian' },
    { name: 'Ibiza', slug: 'ibiza' },
    { name: 'Mallorca', slug: 'mallorca' },
    { name: 'Toledo', slug: 'toledo' },
    { name: 'Cordoba', slug: 'cordoba' },
  ],
  sd: [
    { name: 'Khartoum', slug: 'khartoum' },
    { name: 'Omdurman', slug: 'omdurman' },
    { name: 'Port Sudan', slug: 'port-sudan' },
    { name: 'Kassala', slug: 'kassala' },
    { name: 'Nyala', slug: 'nyala' },
  ],
  sr: [
    { name: 'Paramaribo', slug: 'paramaribo' },
    { name: 'Lelydorp', slug: 'lelydorp' },
    { name: 'Nieuw Nickerie', slug: 'nieuw-nickerie' },
    { name: 'Albina', slug: 'albina' },
  ],
  sj: [
    { name: 'Longyearbyen', slug: 'longyearbyen' },
    { name: 'Barentsburg', slug: 'barentsburg' },
    { name: 'Ny-Ålesund', slug: 'ny-alesund' },
  ],
  se: [
    { name: 'Stockholm', slug: 'stockholm' },
    { name: 'Gothenburg', slug: 'gothenburg' },
    { name: 'Malmö', slug: 'malmo' },
    { name: 'Uppsala', slug: 'uppsala' },
    { name: 'Kiruna', slug: 'kiruna' },
    { name: 'Visby', slug: 'visby' },
    { name: 'Lund', slug: 'lund' },
    { name: 'Are', slug: 'are' },
  ],
  ch: [
    { name: 'Zurich', slug: 'zurich' },
    { name: 'Geneva', slug: 'geneva' },
    { name: 'Bern', slug: 'bern' },
    { name: 'Lucerne', slug: 'lucerne' },
    { name: 'Interlaken', slug: 'interlaken' },
    { name: 'Zermatt', slug: 'zermatt' },
    { name: 'St. Moritz', slug: 'st-moritz' },
    { name: 'Lausanne', slug: 'lausanne' },
    { name: 'Basel', slug: 'basel' },
    { name: 'Lugano', slug: 'lugano' },
  ],
  sy: [
    { name: 'Damascus', slug: 'damascus' },
    { name: 'Aleppo', slug: 'aleppo' },
    { name: 'Latakia', slug: 'latakia' },
    { name: 'Homs', slug: 'homs' },
    { name: 'Palmyra', slug: 'palmyra' },
  ],
  tw: [
    { name: 'Taipei', slug: 'taipei' },
    { name: 'Kaohsiung', slug: 'kaohsiung' },
    { name: 'Taichung', slug: 'taichung' },
    { name: 'Tainan', slug: 'tainan' },
    { name: 'Hualien', slug: 'hualien' },
    { name: 'Taitung', slug: 'taitung' },
    { name: 'Kenting', slug: 'kenting' },
    { name: 'Sun Moon Lake', slug: 'sun-moon-lake' },
  ],
  tj: [
    { name: 'Dushanbe', slug: 'dushanbe' },
    { name: 'Khujand', slug: 'khujand' },
    { name: 'Kulob', slug: 'kulob' },
    { name: 'Khorog', slug: 'khorog' },
    { name: 'Istaravshan', slug: 'istaravshan' },
  ],
  tz: [
    { name: 'Dar es Salaam', slug: 'dar-es-salaam' },
    { name: 'Zanzibar', slug: 'zanzibar' },
    { name: 'Arusha', slug: 'arusha' },
    { name: 'Serengeti', slug: 'serengeti' },
    { name: 'Ngorongoro', slug: 'ngorongoro' },
    { name: 'Dodoma', slug: 'dodoma' },
    { name: 'Mwanza', slug: 'mwanza' },
    { name: 'Kilimanjaro', slug: 'kilimanjaro' },
  ],
  th: [
    { name: 'Bangkok', slug: 'bangkok' },
    { name: 'Phuket', slug: 'phuket' },
    { name: 'Chiang Mai', slug: 'chiang-mai' },
    { name: 'Pattaya', slug: 'pattaya' },
    { name: 'Koh Samui', slug: 'koh-samui' },
    { name: 'Krabi', slug: 'krabi' },
    { name: 'Hua Hin', slug: 'hua-hin' },
    { name: 'Ayutthaya', slug: 'ayutthaya' },
    { name: 'Chiang Rai', slug: 'chiang-rai' },
    { name: 'Kanchanaburi', slug: 'kanchanaburi' },
  ],
  tl: [
    { name: 'Dili', slug: 'dili' },
    { name: 'Baucau', slug: 'baucau' },
    { name: 'Maliana', slug: 'maliana' },
    { name: 'Atauro', slug: 'atauro' },
  ],
  tg: [
    { name: 'Lomé', slug: 'lome' },
    { name: 'Sokodé', slug: 'sokode' },
    { name: 'Kara', slug: 'kara' },
    { name: 'Kpalimé', slug: 'kpalime' },
  ],
  to: [
    { name: "Nuku'alofa", slug: 'nukualofa' },
    { name: 'Neiafu', slug: 'neiafu' },
    { name: 'Haveluloto', slug: 'haveluloto' },
    { name: 'Pangai', slug: 'pangai' },
  ],
  tt: [
    { name: 'Port of Spain', slug: 'port-of-spain' },
    { name: 'San Fernando', slug: 'san-fernando' },
    { name: 'Chaguanas', slug: 'chaguanas' },
    { name: 'Tobago', slug: 'tobago' },
    { name: 'Scarborough', slug: 'scarborough' },
  ],
  tn: [
    { name: 'Tunis', slug: 'tunis' },
    { name: 'Hammamet', slug: 'hammamet' },
    { name: 'Sousse', slug: 'sousse' },
    { name: 'Djerba', slug: 'djerba' },
    { name: 'Sfax', slug: 'sfax' },
    { name: 'Monastir', slug: 'monastir' },
    { name: 'Kairouan', slug: 'kairouan' },
    { name: 'Mahdia', slug: 'mahdia' },
  ],
  tr: [
    { name: 'Istanbul', slug: 'istanbul' },
    { name: 'Ankara', slug: 'ankara' },
    { name: 'Izmir', slug: 'izmir' },
    { name: 'Antalya', slug: 'antalya' },
    { name: 'Bursa', slug: 'bursa' },
    { name: 'Konya', slug: 'konya' },
    { name: 'Adana', slug: 'adana' },
    { name: 'Gaziantep', slug: 'gaziantep' },
    { name: 'Kayseri', slug: 'kayseri' },
    { name: 'Trabzon', slug: 'trabzon' },
    { name: 'Bodrum', slug: 'bodrum' },
    { name: 'Marmaris', slug: 'marmaris' },
    { name: 'Cappadocia', slug: 'cappadocia' },
    { name: 'Pamukkale', slug: 'pamukkale' },
    { name: 'Ephesus', slug: 'ephesus' },
    { name: 'Fethiye', slug: 'fethiye' },
  ],
  tm: [
    { name: 'Ashgabat', slug: 'ashgabat' },
    { name: 'Türkmenbaşy', slug: 'turkmenbasy' },
    { name: 'Mary', slug: 'mary' },
    { name: 'Daşoguz', slug: 'dasoguz' },
    { name: 'Awaza', slug: 'awaza' },
  ],
  tc: [
    { name: 'Providenciales', slug: 'providenciales' },
    { name: 'Cockburn Town', slug: 'cockburn-town' },
    { name: 'Grand Turk', slug: 'grand-turk' },
    { name: 'North Caicos', slug: 'north-caicos' },
    { name: 'Middle Caicos', slug: 'middle-caicos' },
  ],
  ug: [
    { name: 'Kampala', slug: 'kampala' },
    { name: 'Entebbe', slug: 'entebbe' },
    { name: 'Jinja', slug: 'jinja' },
    { name: 'Bwindi', slug: 'bwindi' },
    { name: 'Queen Elizabeth National Park', slug: 'queen-elizabeth-national-park' },
    { name: 'Murchison Falls', slug: 'murchison-falls' },
    { name: 'Mbale', slug: 'mbale' },
  ],
  ua: [
    { name: 'Kyiv', slug: 'kyiv' },
    { name: 'Lviv', slug: 'lviv' },
    { name: 'Odesa', slug: 'odesa' },
    { name: 'Kharkiv', slug: 'kharkiv' },
    { name: 'Dnipro', slug: 'dnipro' },
    { name: 'Chernivtsi', slug: 'chernivtsi' },
    { name: 'Ivano-Frankivsk', slug: 'ivano-frankivsk' },
    { name: 'Bukovel', slug: 'bukovel' },
  ],
  ae: [
    { name: 'Dubai', slug: 'dubai' },
    { name: 'Abu Dhabi', slug: 'abu-dhabi' },
    { name: 'Sharjah', slug: 'sharjah' },
    { name: 'Ajman', slug: 'ajman' },
    { name: 'Ras Al Khaimah', slug: 'ras-al-khaimah' },
    { name: 'Fujairah', slug: 'fujairah' },
    { name: 'Al Ain', slug: 'al-ain' },
    { name: 'Umm Al Quwain', slug: 'umm-al-quwain' },
  ],
  gb: [
    { name: 'London', slug: 'london' },
    { name: 'Manchester', slug: 'manchester' },
    { name: 'Birmingham', slug: 'birmingham' },
    { name: 'Edinburgh', slug: 'edinburgh' },
    { name: 'Glasgow', slug: 'glasgow' },
    { name: 'Liverpool', slug: 'liverpool' },
    { name: 'Leeds', slug: 'leeds' },
    { name: 'Bristol', slug: 'bristol' },
    { name: 'Oxford', slug: 'oxford' },
    { name: 'Cambridge', slug: 'cambridge' },
    { name: 'Bath', slug: 'bath' },
    { name: 'York', slug: 'york' },
    { name: 'Cardiff', slug: 'cardiff' },
    { name: 'Belfast', slug: 'belfast' },
    { name: 'Brighton', slug: 'brighton' },
    { name: 'Nottingham', slug: 'nottingham' },
  ],
  us: [
    { name: 'New York', slug: 'new-york' },
    { name: 'Los Angeles', slug: 'los-angeles' },
    { name: 'Chicago', slug: 'chicago' },
    { name: 'Miami', slug: 'miami' },
    { name: 'Las Vegas', slug: 'las-vegas' },
    { name: 'San Francisco', slug: 'san-francisco' },
    { name: 'Houston', slug: 'houston' },
    { name: 'Washington', slug: 'washington' },
    { name: 'Boston', slug: 'boston' },
    { name: 'Seattle', slug: 'seattle' },
    { name: 'New Orleans', slug: 'new-orleans' },
    { name: 'Orlando', slug: 'orlando' },
    { name: 'Denver', slug: 'denver' },
    { name: 'Nashville', slug: 'nashville' },
    { name: 'Atlanta', slug: 'atlanta' },
    { name: 'Phoenix', slug: 'phoenix' },
    { name: 'Dallas', slug: 'dallas' },
    { name: 'San Diego', slug: 'san-diego' },
    { name: 'Portland', slug: 'portland' },
    { name: 'Austin', slug: 'austin' },
  ],
  uy: [
    { name: 'Montevideo', slug: 'montevideo' },
    { name: 'Punta del Este', slug: 'punta-del-este' },
    { name: 'Colonia del Sacramento', slug: 'colonia-del-sacramento' },
    { name: 'Salto', slug: 'salto' },
    { name: 'Piriápolis', slug: 'piriapolis' },
    { name: 'José Ignacio', slug: 'jose-ignacio' },
  ],
  vi: [
    { name: 'Charlotte Amalie', slug: 'charlotte-amalie' },
    { name: 'Christiansted', slug: 'christiansted' },
    { name: 'Frederiksted', slug: 'frederiksted' },
    { name: 'Cruz Bay', slug: 'cruz-bay' },
  ],
  uz: [
    { name: 'Tashkent', slug: 'tashkent' },
    { name: 'Samarkand', slug: 'samarkand' },
    { name: 'Bukhara', slug: 'bukhara' },
    { name: 'Khiva', slug: 'khiva' },
    { name: 'Fergana', slug: 'fergana' },
    { name: 'Namangan', slug: 'namangan' },
  ],
  vu: [
    { name: 'Port Vila', slug: 'port-vila' },
    { name: 'Luganville', slug: 'luganville' },
    { name: 'Isangel', slug: 'isangel' },
    { name: 'Lakatoro', slug: 'lakatoro' },
  ],
  va: [
    { name: 'Vatican City', slug: 'vatican-city' },
  ],
  ve: [
    { name: 'Caracas', slug: 'caracas' },
    { name: 'Maracaibo', slug: 'maracaibo' },
    { name: 'Valencia', slug: 'valencia' },
    { name: 'Margarita Island', slug: 'margarita-island' },
    { name: 'Mérida', slug: 'merida' },
    { name: 'Canaima', slug: 'canaima' },
    { name: 'Los Roques', slug: 'los-roques' },
  ],
  vn: [
    { name: 'Hanoi', slug: 'hanoi' },
    { name: 'Ho Chi Minh City', slug: 'ho-chi-minh-city' },
    { name: 'Da Nang', slug: 'da-nang' },
    { name: 'Hoi An', slug: 'hoi-an' },
    { name: 'Nha Trang', slug: 'nha-trang' },
    { name: 'Phu Quoc', slug: 'phu-quoc' },
    { name: 'Ha Long Bay', slug: 'ha-long-bay' },
    { name: 'Sapa', slug: 'sapa' },
    { name: 'Hue', slug: 'hue' },
    { name: 'Dalat', slug: 'dalat' },
    { name: 'Mui Ne', slug: 'mui-ne' },
  ],
  wf: [
    { name: 'Mata-Utu', slug: 'mata-utu' },
    { name: 'Leava', slug: 'leava' },
    { name: 'Alo', slug: 'alo' },
  ],
  ye: [
    { name: "Sana'a", slug: 'sanaa' },
    { name: 'Aden', slug: 'aden' },
    { name: 'Taiz', slug: 'taiz' },
    { name: 'Hodeidah', slug: 'hodeidah' },
    { name: 'Mukalla', slug: 'mukalla' },
    { name: 'Socotra', slug: 'socotra' },
  ],
  zm: [
    { name: 'Lusaka', slug: 'lusaka' },
    { name: 'Livingstone', slug: 'livingstone' },
    { name: 'Ndola', slug: 'ndola' },
    { name: 'Kitwe', slug: 'kitwe' },
    { name: 'Kafue', slug: 'kafue' },
    { name: 'South Luangwa', slug: 'south-luangwa' },
  ],
};

export default CITIES;
